##
##  Makefile -- Build procedure for sample selinux Apache module
##  Autogenerated via ``apxs -n selinux -g''.
##

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   defines the base directories
builddir=.
top_srcdir=/etc/httpd
top_builddir=$(shell $(APXS) -q libdir)/httpd
include $(top_builddir)/build/special.mk

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_selinux.o mod_selinux.lo mod_selinux.slo mod_selinux.la
	test -e /usr/share/selinux/devel/Makefile && $(MAKE) -f /usr/share/selinux/devel/Makefile clean

#   simple test
test: reload
	lynx -mime_header http://localhost/selinux

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

